version: "3.8"

services:
  find-pc:
    image: ${find_pc_image}
    container_name: find-pc
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8888:80"
      - "443:443"
    volumes:
      - ${nginx_config_path}:/etc/nginx/conf.d/default.conf:ro
      - ${nginx_ssl_path}:/etc/nginx/ssl:ro
    depends_on:
      - find-pc
    networks:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password}
      MYSQL_DATABASE: ${db_name}
    ports:
      - "3306:3306"

    networks:
      - backend

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  db_data:

networks:
  backend: